# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile

-keep class net.sourceforge.jtds.** { *; }
-dontwarn net.sourceforge.jtds.**

# Google API/Drive client (google-api-client ships no consumer rules and maps JSON via
# reflection on @Key-annotated fields; R8 would otherwise strip/rename them and break uploads).
-keepattributes Signature,*Annotation*,EnclosingMethod
-keep class com.google.api.client.** { *; }
-keep class com.google.api.services.drive.** { *; }
-keepclassmembers class * { @com.google.api.client.util.Key <fields>; }
-dontwarn com.google.api.client.**
-dontwarn com.google.api.services.drive.**
-dontwarn org.apache.http.**
-dontwarn javax.**

# Gson (used by GsonFactory to (de)serialize the Drive model classes)
-keep class com.google.gson.** { *; }
-dontwarn com.google.gson.**

# Rules generated by R8 for missing classes
-dontwarn com.azure.core.credential.AccessToken
-dontwarn com.azure.core.credential.TokenCredential
-dontwarn com.azure.core.credential.TokenRequestContext
-dontwarn com.azure.core.http.HttpPipeline
-dontwarn com.azure.core.http.HttpPipelineBuilder
-dontwarn com.azure.core.http.policy.HttpLogOptions
-dontwarn com.azure.core.http.policy.HttpLoggingPolicy
-dontwarn com.azure.core.http.policy.HttpPipelinePolicy
-dontwarn com.azure.core.http.policy.HttpPolicyProviders
-dontwarn com.azure.core.http.policy.RetryPolicy
-dontwarn com.azure.identity.DefaultAzureCredential
-dontwarn com.azure.identity.DefaultAzureCredentialBuilder
-dontwarn com.azure.identity.ManagedIdentityCredential
-dontwarn com.azure.identity.ManagedIdentityCredentialBuilder
-dontwarn com.azure.security.keyvault.keys.KeyClient
-dontwarn com.azure.security.keyvault.keys.KeyClientBuilder
-dontwarn com.azure.security.keyvault.keys.cryptography.CryptographyClient
-dontwarn com.azure.security.keyvault.keys.cryptography.CryptographyClientBuilder
-dontwarn com.azure.security.keyvault.keys.cryptography.models.KeyWrapAlgorithm
-dontwarn com.azure.security.keyvault.keys.cryptography.models.SignResult
-dontwarn com.azure.security.keyvault.keys.cryptography.models.SignatureAlgorithm
-dontwarn com.azure.security.keyvault.keys.cryptography.models.UnwrapResult
-dontwarn com.azure.security.keyvault.keys.cryptography.models.VerifyResult
-dontwarn com.azure.security.keyvault.keys.models.JsonWebKey
-dontwarn com.azure.security.keyvault.keys.models.KeyType
-dontwarn com.azure.security.keyvault.keys.models.KeyVaultKey
-dontwarn com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder
-dontwarn com.microsoft.aad.msal4j.ClientCredentialFactory
-dontwarn com.microsoft.aad.msal4j.ClientCredentialParameters$ClientCredentialParametersBuilder
-dontwarn com.microsoft.aad.msal4j.ClientCredentialParameters
-dontwarn com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder
-dontwarn com.microsoft.aad.msal4j.ConfidentialClientApplication
-dontwarn com.microsoft.aad.msal4j.IAccount
-dontwarn com.microsoft.aad.msal4j.IAuthenticationResult
-dontwarn com.microsoft.aad.msal4j.IClientCertificate
-dontwarn com.microsoft.aad.msal4j.IClientCredential
-dontwarn com.microsoft.aad.msal4j.IClientSecret
-dontwarn com.microsoft.aad.msal4j.ITokenCacheAccessAspect
-dontwarn com.microsoft.aad.msal4j.IntegratedWindowsAuthenticationParameters$IntegratedWindowsAuthenticationParametersBuilder
-dontwarn com.microsoft.aad.msal4j.IntegratedWindowsAuthenticationParameters
-dontwarn com.microsoft.aad.msal4j.InteractionRequiredExceptionReason
-dontwarn com.microsoft.aad.msal4j.InteractiveRequestParameters$InteractiveRequestParametersBuilder
-dontwarn com.microsoft.aad.msal4j.InteractiveRequestParameters
-dontwarn com.microsoft.aad.msal4j.MsalInteractionRequiredException
-dontwarn com.microsoft.aad.msal4j.PublicClientApplication$Builder
-dontwarn com.microsoft.aad.msal4j.PublicClientApplication
-dontwarn com.microsoft.aad.msal4j.SilentParameters$SilentParametersBuilder
-dontwarn com.microsoft.aad.msal4j.SilentParameters
-dontwarn com.microsoft.aad.msal4j.SystemBrowserOptions$SystemBrowserOptionsBuilder
-dontwarn com.microsoft.aad.msal4j.SystemBrowserOptions
-dontwarn com.microsoft.aad.msal4j.UserNamePasswordParameters$UserNamePasswordParametersBuilder
-dontwarn com.microsoft.aad.msal4j.UserNamePasswordParameters
-dontwarn java.beans.Transient
-dontwarn java.lang.ProcessHandle
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.MemoryMXBean
-dontwarn java.lang.management.MemoryUsage
-dontwarn org.antlr.v4.runtime.ANTLRErrorListener
-dontwarn org.antlr.v4.runtime.BaseErrorListener
-dontwarn org.antlr.v4.runtime.CharStream
-dontwarn org.antlr.v4.runtime.CharStreams
-dontwarn org.antlr.v4.runtime.Lexer
-dontwarn org.antlr.v4.runtime.RuntimeMetaData
-dontwarn org.antlr.v4.runtime.Token
-dontwarn org.antlr.v4.runtime.Vocabulary
-dontwarn org.antlr.v4.runtime.VocabularyImpl
-dontwarn org.antlr.v4.runtime.atn.ATN
-dontwarn org.antlr.v4.runtime.atn.ATNDeserializer
-dontwarn org.antlr.v4.runtime.atn.ATNSimulator
-dontwarn org.antlr.v4.runtime.atn.DecisionState
-dontwarn org.antlr.v4.runtime.atn.LexerATNSimulator
-dontwarn org.antlr.v4.runtime.atn.PredictionContextCache
-dontwarn org.antlr.v4.runtime.dfa.DFA
-dontwarn org.bouncycastle.jce.provider.BouncyCastleProvider
-dontwarn org.bouncycastle.openssl.PEMDecryptorProvider
-dontwarn org.bouncycastle.openssl.PEMEncryptedKeyPair
-dontwarn org.bouncycastle.openssl.PEMKeyPair
-dontwarn org.bouncycastle.openssl.PEMParser
-dontwarn org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter
-dontwarn org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder
-dontwarn org.ietf.jgss.ChannelBinding
-dontwarn org.ietf.jgss.GSSContext
-dontwarn org.ietf.jgss.GSSCredential
-dontwarn org.ietf.jgss.GSSException
-dontwarn org.ietf.jgss.GSSManager
-dontwarn org.ietf.jgss.GSSName
-dontwarn org.ietf.jgss.Oid
-dontwarn reactor.core.publisher.FluxSink$OverflowStrategy
-dontwarn reactor.core.publisher.FluxSink
-dontwarn reactor.core.publisher.Mono
-dontwarn reactor.core.publisher.ReplayProcessor
